version: "3.8"
services:
  api:
    image: node:18-alpine
    container_name: node-mongo-api
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: node-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
