services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=
      - N8N_AUTH_EXCLUDE_ENDPOINTS=webhook
      - N8N_ENCRYPTION_KEY=
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=
      - N8N_METRICS=true
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - n8n-net

volumes:
  n8n-data:
    driver: local
    name: n8n-data
networks:
  n8n-net:
    driver: bridge
    name: n8n-net
