server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: syslog
  static_configs:
  - targets: [ localhost ]
    labels:
      job: syslog
      __path__: /var/log/syslog

- job_name: auth
  static_configs:
  - targets: [ localhost ]
    labels:
      job: auth
      __path__: /var/log/auth.log

- job_name: nginx
  static_configs:
  - targets: [ localhost ]
    labels:
      job: nginx
      __path__: /var/log/nginx/*.log
