version: "3.8"
services:
  web:
    image: node:14-alpine
    container_name: node-mongo-web
    volumes:
      - ./blog-app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - NODE_ENV=development
    restart: always
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: mongo:4.4
    container_name: node-mongo-db
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=blog
    networks:
      - blog-network

volumes:
  mongo-data:
    driver: local

networks:
  blog-network:
    driver: bridge
