version: "3.8"
services:
  php:
    image: php:8.2-apache
    container_name: php
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=userku
      - MYSQL_PASSWORD=passku
      - MYSQL_DATABASE=dbku
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=userku
      - PMA_PASSWORD=passku

volumes:
  mysql-data:
    driver: local
